using System;
using System.Diagnostics;
using System.IO;
using System.Web;
using System.Windows;
using System.Windows.Navigation;
using BravoLights.Installation;

namespace BravoLights.UI
{
    /// <summary>
    /// Interaction logic for CorruptExeXmlErrorWindow.xaml
    /// </summary>
    public partial class CorruptExeXmlErrorWindow : Window
    {
        public CorruptExeXmlErrorWindow()
        {
            InitializeComponent();
        }

        private void Hyperlink_RequestNavigate(object sender, RequestNavigateEventArgs e)
        {
            e.Handled = true;
            Process.Start(new ProcessStartInfo(e.Uri.AbsoluteUri) { UseShellExecute = true });
        }

        private void ShowExeXmlLocation(object sender, RequestNavigateEventArgs e)
        {
            e.Handled = true;
            Process.Start(new ProcessStartInfo(Path.GetDirectoryName(XmlFilename)) { UseShellExecute = true });
        }

        private void RaiseExeXmlIssue(object sender, RequestNavigateEventArgs e)
        {
            var softwareVersion = ProgramInfo.VersionString;
            var title = "Can you help fix my corrupt exe.xml file?";

            var errorText = Exception.InnerException.Message;
            var exeXmlContents = string.Join('\n', File.ReadAllText(XmlFilename));

            var issueBody = $@"
<!-- Please take a look through this report, which has been automatically generated by BetterBravoLights.
     It should contain enough information to help us fix your corrupted file, but may wish to scan
     through it to ensure it doesn't contain any personal information you don't wish to share.
-->

**Software version**
{softwareVersion}

**Problem**
BetterBravoLights refused to install because my `exe.xml` file is corrupt.

My `exe.xml` file is located at
`{XmlFilename}`

The error reported was
```
{errorText}
```


The contents of the `exe.xml` file are as follows:

```xml
{exeXmlContents}
```

I understand that BetterBravoLights didn't corrupt the file and that it's simply warning
about the corrupted file. But could you help me fix it?
";
            var queryParams = HttpUtility.ParseQueryString(string.Empty);
            queryParams["labels"] = "exe-xml-help";
            queryParams["title"] = title;
            queryParams["body"] = issueBody;

            var uriBuilder = new UriBuilder("https://github.com/RoystonS/BetterBravoLights/issues/new")
            {
                Query = queryParams.ToString()
            };

            var uri = uriBuilder.ToString();

            e.Handled = true;
            Process.Start(new ProcessStartInfo(uri) { UseShellExecute = true });
        }

        public static readonly DependencyProperty XmlFilenameProperty = DependencyProperty.Register("XmlFilename", typeof(string), typeof(CorruptExeXmlErrorWindow));
        public string XmlFilename
        {
            get { return (string)GetValue(XmlFilenameProperty); }
            set { SetValue(XmlFilenameProperty, value); }
        }

        public static readonly DependencyProperty ExceptionProperty = DependencyProperty.Register("Exception", typeof(CorruptExeXmlException), typeof(CorruptExeXmlErrorWindow));
        public CorruptExeXmlException Exception
        {
            get { return (CorruptExeXmlException)GetValue(ExceptionProperty); }
            set { SetValue(ExceptionProperty, value); }
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }

    }
}
